# Generated by Django 4.0.5 on 2022-07-07 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['street']},
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(default='Cuba', max_length=50, verbose_name='Country'),
        ),
    ]
